require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SalesrepsController do

  # This should return the minimal set of attributes required to create a valid
  # Salesrep. As you add validations to Salesrep, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SalesrepsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all salesreps as @salesreps" do
      salesrep = Salesrep.create! valid_attributes
      get :index, {}, valid_session
      assigns(:salesreps).should eq([salesrep])
    end
  end

  describe "GET show" do
    it "assigns the requested salesrep as @salesrep" do
      salesrep = Salesrep.create! valid_attributes
      get :show, {:id => salesrep.to_param}, valid_session
      assigns(:salesrep).should eq(salesrep)
    end
  end

  describe "GET new" do
    it "assigns a new salesrep as @salesrep" do
      get :new, {}, valid_session
      assigns(:salesrep).should be_a_new(Salesrep)
    end
  end

  describe "GET edit" do
    it "assigns the requested salesrep as @salesrep" do
      salesrep = Salesrep.create! valid_attributes
      get :edit, {:id => salesrep.to_param}, valid_session
      assigns(:salesrep).should eq(salesrep)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Salesrep" do
        expect {
          post :create, {:salesrep => valid_attributes}, valid_session
        }.to change(Salesrep, :count).by(1)
      end

      it "assigns a newly created salesrep as @salesrep" do
        post :create, {:salesrep => valid_attributes}, valid_session
        assigns(:salesrep).should be_a(Salesrep)
        assigns(:salesrep).should be_persisted
      end

      it "redirects to the created salesrep" do
        post :create, {:salesrep => valid_attributes}, valid_session
        response.should redirect_to(Salesrep.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved salesrep as @salesrep" do
        # Trigger the behavior that occurs when invalid params are submitted
        Salesrep.any_instance.stub(:save).and_return(false)
        post :create, {:salesrep => { "name" => "invalid value" }}, valid_session
        assigns(:salesrep).should be_a_new(Salesrep)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Salesrep.any_instance.stub(:save).and_return(false)
        post :create, {:salesrep => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested salesrep" do
        salesrep = Salesrep.create! valid_attributes
        # Assuming there are no other salesreps in the database, this
        # specifies that the Salesrep created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Salesrep.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => salesrep.to_param, :salesrep => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested salesrep as @salesrep" do
        salesrep = Salesrep.create! valid_attributes
        put :update, {:id => salesrep.to_param, :salesrep => valid_attributes}, valid_session
        assigns(:salesrep).should eq(salesrep)
      end

      it "redirects to the salesrep" do
        salesrep = Salesrep.create! valid_attributes
        put :update, {:id => salesrep.to_param, :salesrep => valid_attributes}, valid_session
        response.should redirect_to(salesrep)
      end
    end

    describe "with invalid params" do
      it "assigns the salesrep as @salesrep" do
        salesrep = Salesrep.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Salesrep.any_instance.stub(:save).and_return(false)
        put :update, {:id => salesrep.to_param, :salesrep => { "name" => "invalid value" }}, valid_session
        assigns(:salesrep).should eq(salesrep)
      end

      it "re-renders the 'edit' template" do
        salesrep = Salesrep.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Salesrep.any_instance.stub(:save).and_return(false)
        put :update, {:id => salesrep.to_param, :salesrep => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested salesrep" do
      salesrep = Salesrep.create! valid_attributes
      expect {
        delete :destroy, {:id => salesrep.to_param}, valid_session
      }.to change(Salesrep, :count).by(-1)
    end

    it "redirects to the salesreps list" do
      salesrep = Salesrep.create! valid_attributes
      delete :destroy, {:id => salesrep.to_param}, valid_session
      response.should redirect_to(salesreps_url)
    end
  end

end
